CREATE TABLE ENDERECO (
  ID_ENDERECO NUMBER(5) NOT NULL,
  LOGRADOURO VARCHAR2(255) NOT NULL,
  NUMERO NUMBER(6) NOT NULL,
  COMPLEMENTO VARCHAR2(255),
  CIDADE VARCHAR2(255) NOT NULL,
  ESTADO VARCHAR2(255) NOT NULL,
  CEP VARCHAR2(9) NOT NULL,
  PRIMARY KEY (ID_ENDERECO)
);

CREATE SEQUENCE SEQ_ENDERECO
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE PROFESSOR (
  ID_PROFESSOR NUMBER(5) NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  TELEFONE VARCHAR2(13) NOT NULL,
  EMAIL VARCHAR2(255) NOT NULL,
  REGISTRO_TRABALHO NUMBER(12) NOT NULL,
  CARGO VARCHAR2(255) NOT NULL,
  SALÁRIO DECIMAL(7,2) NOT NULL,
  ID_ENDERECO NUMBER(5),
  PRIMARY KEY (ID_PROFESSOR),
  CONSTRAINT FK_PROFESSOR_ID_ENDERECO
    FOREIGN KEY (ID_ENDERECO)
      REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE SEQUENCE SEQ_PROFESSOR
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE SEQUENCE SEQ_REGISTRO_TRABALHO
START WITH 1000
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE DISCIPLINA (
  ID_DISCIPLINA NUMBER(5) NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  ID_PROFESSOR NUMBER(5),
  PRIMARY KEY (ID_DISCIPLINA),
  CONSTRAINT FK_DISCIPLINA_ID_PROFESSOR
    FOREIGN KEY (ID_PROFESSOR)
      REFERENCES PROFESSOR(ID_PROFESSOR)
);

CREATE SEQUENCE SEQ_DISCIPLINA
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE CURSO (
  ID_CURSO NUMBER(5) NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_CURSO)
);

CREATE SEQUENCE SEQ_CURSO
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE ALUNO (
  ID_ALUNO NUMBER(12) NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  TELEFONE VARCHAR2(13) NOT NULL,
  EMAIL VARCHAR2(255) NOT NULL,
  MATRICULA NUMBER(16) NOT NULL,
  ID_CURSO NUMBER(5),
  ID_ENDERECO NUMBER(5),
  PRIMARY KEY (ID_ALUNO),
  CONSTRAINT FK_ALUNO_ID_CURSO
    FOREIGN KEY (ID_CURSO)
      REFERENCES CURSO(ID_CURSO),
  CONSTRAINT FK_ALUNO_ID_ENDERECO
    FOREIGN KEY (ID_ENDERECO)
      REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE SEQUENCE SEQ_ALUNO
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE SEQUENCE SEQ_ALUNO_MATRICULA
START WITH 1000
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE NOTAS (
  ID_NOTAS NUMBER(20) NOT NULL,
  N1 DECIMAL(4, 2),
  N2 DECIMAL(4, 2),
  N3 DECIMAL(4, 2),
  N4 DECIMAL(4, 2),
  MEDIA DECIMAL(4, 2),
  ID_DISCIPLINA NUMBER(5) NOT NULL,
  ID_ALUNO NUMBER(12) NOT NULL,
  PRIMARY KEY (ID_NOTAS),
  CONSTRAINT FK_NOTAS_ID_ALUNO
    FOREIGN KEY (ID_ALUNO)
      REFERENCES ALUNO(ID_ALUNO),
  CONSTRAINT FK_NOTAS_ID_DISCIPLINA
    FOREIGN KEY (ID_DISCIPLINA)
      REFERENCES DISCIPLINA(ID_DISCIPLINA)
);

CREATE SEQUENCE SEQ_NOTAS
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE DISCIPLINA_X_CURSO (
  ID_DISCIPLINA_X_CURSO NUMBER(5) NOT NULL,
  ID_DISCIPLINA NUMBER(5) NOT NULL,
  ID_CURSO NUMBER(5) NOT NULL,
  PRIMARY KEY (ID_DISCIPLINA_X_CURSO),
  CONSTRAINT FK_DISCIPLINA_X_CURSO_ID_CURSO
    FOREIGN KEY (ID_CURSO)
      REFERENCES CURSO(ID_CURSO),
  CONSTRAINT FK_D_X_C_ID_DISCIPLINA
    FOREIGN KEY (ID_DISCIPLINA)
      REFERENCES DISCIPLINA(ID_DISCIPLINA)
);

CREATE SEQUENCE SEQ_DISCIPLINA_X_CURSO
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

INSERT INTO VEMSER_JEAN.ENDERECO (ID_ENDERECO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, ESTADO, CEP) 
VALUES (SEQ_ENDERECO.nextval, 'Rua das Ruas', 8, 'Apartament 30', 'São Paulo', 'São Paulo','02256-325');

INSERT INTO VEMSER_JEAN.ENDERECO (ID_ENDERECO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, ESTADO, CEP) 
VALUES (SEQ_ENDERECO.nextval, 'Rua das Máquinas', 22, NULL, 'São Paulo', 'São Paulo','05586-325');

INSERT INTO VEMSER_JEAN.PROFESSOR (ID_PROFESSOR, NOME, TELEFONE, EMAIL, REGISTRO_TRABALHO, CARGO, SALÁRIO, ID_ENDERECO)
VALUES (SEQ_PROFESSOR.nextval, 'José Antônio', '5511999995555', 'jose.antonio@gmail.com', SEQ_REGISTRO_TRABALHO.nextval, 'Professor', 5500, 1);

INSERT INTO VEMSER_JEAN.CURSO (ID_CURSO, NOME)
VALUES (SEQ_CURSO.nextval, 'Engenharia Mecânica');

INSERT INTO VEMSER_JEAN.DISCIPLINA (ID_DISCIPLINA, NOME, ID_PROFESSOR) 
VALUES (SEQ_DISCIPLINA.nextval, 'Física', 1);

INSERT INTO VEMSER_JEAN.ALUNO (ID_ALUNO, NOME, TELEFONE, EMAIL, MATRICULA, ID_CURSO, ID_ENDERECO)
VALUES (SEQ_ALUNO.nextval, 'Fernando Fernandes', '5522888883333', 'fernando.fernandes@gmail.com', SEQ_ALUNO_MATRICULA.nextval, 1, 2);

INSERT INTO VEMSER_JEAN.NOTAS (ID_NOTAS, N1, N2, N3, N4, MEDIA, ID_DISCIPLINA, ID_ALUNO)
VALUES (SEQ_NOTAS.nextval, NULL, NULL, NULL, NULL, NULL, 1, 1)

INSERT INTO VEMSER_JEAN.DISCIPLINA_X_CURSO (ID_DISCIPLINA_X_CURSO, ID_DISCIPLINA, ID_CURSO)
VALUES (SEQ_DISCIPLINA_X_CURSO.nextval, 1, 1);

SELECT * FROM CURSO;
SELECT * FROM ENDERECO;



DROP TABLE DISCIPLINA_X_CURSO;
DROP TABLE NOTAS;
DROP TABLE ALUNO;
DROP TABLE DISCIPLINA;
DROP TABLE CURSO;
DROP TABLE PROFESSOR;
DROP TABLE ENDERECO;

TRUNCATE TABLE ENDERECO;
